### ISSUE TITLE
问题请求

### ISSUE THREAD

**Issue by JYC1213** [Lee-Carl/unmixing_python#2]
李先生您好，首先非常感谢您所分享的unmixing代码，我目前所选择的研究方向也是混合像元分解，您的代码对我提供了很大的帮助，非常感谢您，并且通过您分享的HySuPP文章链接我学习了HySuPP软件包，尝试进行使用，但我在使用过程中遇到了如下问题，请问您能帮我解决这个问题吗？十分感谢您的帮助，我根据他所提供的Readme指示构建了虚拟环境，并且安装好了所需的各种库，但运行python unmixing.py mode=semi data=DC1 model=SUnCNN时发生了报错，请问我该如何解决呢？谢谢您。
(hysupp) PS E:\pytorchtest\HySUPP-main\HySuPP\HySuPP> python unmixing.py mode=semi data=DC1 model=SUnCNN projection=True
Error executing job with overrides: ['mode=semi', 'data=DC1', 'model=SUnCNN', 'projection=True']
Traceback (most recent call last):
  File "E:\pytorchtest\HySUPP-main\HySuPP\HySuPP\unmixing.py", line 160, in decorated_task
  File "C:\Users\asus\.conda\envs\hysupp\lib\site-packages\mlxp\_internal\configure.py", line 42, in _build_config
    default_cfg = _get_default_config(config_path)
  File "C:\Users\asus\.conda\envs\hysupp\lib\site-packages\mlxp\_internal\configure.py", line 102, in _get_default_config
    mlxp_config = _get_mlxp_configs(mlxp_file, default_config["mlxp"])
    mlxp_config = _get_mlxp_configs(mlxp_file, default_config["mlxp"])
  File "C:\Users\asus\.conda\envs\hysupp\lib\site-packages\mlxp\_internal\configure.py", line 88, in _get_mlxp_configs
    raise InvalidConfigFileError(msg) from None
mlxp.errors.InvalidConfigFileError: The following mlxp file is corrupted: E:\pytorchtest\HySUPP-main\HySuPP\HySuPP\config\mlxp.yaml,It contains an invalid field: scheduler
Valid fields are ['logger', 'version_manager', 'use_version_manager', 'use_scheduler', 'use_logger', 'interactive_mode', 'resolve', 'as_ConfigDict']
![QQ截图20241009103336](https://github.com/user-attachments/assets/af472d5b-a744-4d45-9754-5ca00adc1cec)

**Comment by flyzzie** [comment]
Same problem, have u figured it out?

**Comment by Lee-Carl** [comment]
很高兴分享的资料对你有帮助。因为参加工作了，比较忙，所以我是最近才注意到你的issue的。对于你的问题，你其实应该问下这个代码库的创建者，而不是我。我刚刚试了试以前安装的针对HySUPP环境，我发现并没有遇到你这样的问题，做的唯一改动是把这个方法所需要的迭代次数调低了:
![Snipaste_2024-11-17_22-04-48](https://github.com/user-attachments/assets/cef8e2a2-246e-47c0-b6f6-d9667e21151d)
看你发的图，控制台的报错的内容应该是mlxp.yaml这个文件上有个字段不是预期的值了，用断点调试一下。如果你还没有解决这个问题，建议问问原作者。 @JYC1213
